# Generated by Django 4.1 on 2022-08-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imag',
            new_name='image',
        ),
    ]
