# Generated by Django 4.1 on 2022-08-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_name', models.CharField(max_length=100)),
                ('about_me', models.CharField(max_length=10000)),
                ('imag', models.ImageField(upload_to='about/%y/%m/%d')),
                ('subtitle', models.TextField(max_length=500)),
                ('tw_link', models.URLField()),
                ('git_link', models.URLField()),
                ('in_link', models.URLField()),
            ],
        ),
    ]
