# Generated by Django 4.1 on 2022-08-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_me',
            field=models.TextField(max_length=10000),
        ),
    ]
